# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-updates

version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "docker/login-action"
        versions: [">1.9.0"]
      - dependency-name: "docker/metadata-action"
        versions: [">3.3.0"]
      - dependency-name: "docker/build-push-action"
        versions: [">2.10.0"]
      - dependency-name: "sigstore/cosign-installer"
        versions: ["2.2.0"]
