version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fantasy-baseball-buzz
    ports:
      - "5000:5000"
    environment:
      - TZ=America/New_York
      - AIRTABLE_API_KEY={{YOUR_VALUE}}
      - AIRTABLE_BASE_ID={{YOUR_VALUE}}
      - AIRTABLE_TABLE_NAME={{YOUR_VALUE}}
      - ESPN_LOGIN_EMAIL={{YOUR_VALUE}}
      - ESPN_LOGIN_PASSWORD={{YOUR_VALUE}}
      - ESPN_LEAGUE_ID={{YOUR_VALUE}}
      - ESPN_TEAM_NAME={{YOUR_VALUE}}
      - ESPN_TEAM_ABBREVIATION={{YOUR_VALUE}}
