version: "3.9"
services:
  web:
    image: fantasy-baseball-buzz:main 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fantasy-baseball-buzz
    ports:
      - "5000:5000"
