# https://github.com/peter-evans/docker-compose-actions-workflow

name: Docker Compose

on:
  schedule:
    - cron: '22 22 * * 3'
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build the stack
      run: docker-compose up -d

    - name: Test the compose file
      run: docker run --network container:fantasy-baseball-buzz appropriate/curl --verbose --retry 10 --retry-connrefused http://localhost:5000
