# https://github.com/actions/starter-workflows/blob/main/ci/docker-image.yml

name: Docker Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '**.py'
      - 'Pipfile'
      - 'Pipfile.lock'
      - '**.html'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '**.py'
      - 'Pipfile'
      - 'Pipfile.lock'
      - '**.html'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
