# https://github.com/actions/starter-workflows/blob/main/ci/python-app.yml

name: Python Application

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Pipfile'
      - 'Pipfile.lock'
      - 'src/**'
      - 'static/**'
      - 'templates/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'Pipfile'
      - 'Pipfile.lock'
      - 'src/**'
      - 'static/**'
      - 'templates/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.3"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pipenv'

    - name: Install dependencies
      run: |
        python -m pip install pipenv
        pipenv install --deploy

    - name: Lint with flake8
      run: |
        pipenv install flake8
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
